

class LocalizationService {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Listy',
      'settings_title': 'App Settings',
      'language_label': 'Language',
      'ai_config_title': 'AI Configuration',
      'ai_provider_label': 'AI Provider',
      'api_key_label': 'API Key',
      'verify_connection': 'Verify Connection',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'new_list': 'New List',
      'rename_list': 'Rename List',
      'delete_list': 'Delete List',
      'add_task_hint': 'Add Task...',
      'add_item_hint': 'Add Item...',
      'clear_list': 'Clear List',
      'clear_completed': 'Clear Completed',
      'mode_todo': 'To-Do Mode',
      'mode_shopping': 'Shopping Mode',
      'urgent': 'Urgent',
      'medium': 'Medium',
      'low': 'Low',
      'open': 'Open',
      'cart': 'In Cart',
      'no_tasks': 'No tasks',
      'empty_cart': 'Empty Cart',
      'confirm_clear_list': 'Remove ALL items from this list?',
      'confirm_empty_cart': 'Remove all items from cart?',
      'confirm_clear_completed': 'Remove all completed tasks?',
      'camera_source_camera': 'Camera',
      'camera_source_gallery': 'Gallery',
      'task_completed_msg': 'Task completed!',
    },
    'de': {
      'app_title': 'Listy',
      'settings_title': 'App Einstellungen',
      'language_label': 'Sprache',
      'ai_config_title': 'AI Konfiguration',
      'ai_provider_label': 'AI Provider',
      'api_key_label': 'API Key',
      'verify_connection': 'Verbindung prüfen',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'new_list': 'Neue Liste',
      'rename_list': 'Liste umbenennen',
      'delete_list': 'Liste löschen',
      'add_task_hint': 'Neue Aufgabe...',
      'add_item_hint': 'Neuer Artikel...',
      'clear_list': 'Liste leeren',
      'clear_completed': 'Erledigt löschen',
      'mode_todo': 'To-Do Modus',
      'mode_shopping': 'Einkaufsmodus',
      'urgent': 'Wichtig',
      'medium': 'Relevant',
      'low': 'Unwichtig',
      'open': 'Offen',
      'cart': 'Im Warenkorb',
      'no_tasks': 'Keine Aufgaben',
      'empty_cart': 'Warenkorb leeren',
      'confirm_clear_list': 'Alle Einträge von dieser Liste entfernen?',
      'confirm_empty_cart': 'Alle Artikel aus dem Warenkorb entfernen?',
      'confirm_clear_completed': 'Alle erledigten Aufgaben löschen?',
      'camera_source_camera': 'Kamera',
      'camera_source_gallery': 'Galerie',
      'task_completed_msg': 'Aufgabe wurde erledigt !',
    },
    'ja': {
      'app_title': 'Listy',
      'settings_title': 'アプリ設定',
      'language_label': '言語',
      'ai_config_title': 'AI設定',
      'ai_provider_label': 'AIプロバイダー',
      'api_key_label': 'APIキー',
      'verify_connection': '接続を確認',
      'save': '保存',
      'cancel': 'キャンセル',
      'delete': '削除',
      'new_list': '新しいリスト',
      'rename_list': 'リスト名を変更',
      'delete_list': 'リストを削除',
      'add_task_hint': 'タスクを追加...',
      'add_item_hint': 'アイテムを追加...',
      'clear_list': 'リストをクリア',
      'clear_completed': '完了済みを削除',
      'mode_todo': 'To-Doモード',
      'mode_shopping': '買い物モード',
      'urgent': '緊急',
      'medium': '中',
      'low': '低',
      'open': '未完了',
      'cart': 'カート内',
      'no_tasks': 'タスクなし',
      'empty_cart': 'カートを空にする',
      'confirm_clear_list': 'このリストからすべてのアイテムを削除しますか?',
      'confirm_empty_cart': 'カートからすべてのアイテムを削除しますか?',
      'confirm_clear_completed': '完了したタスクをすべて削除しますか?',
      'camera_source_camera': 'カメラ',
      'camera_source_gallery': 'ギャラリー',
      'task_completed_msg': 'タスク完了！',
    },
    'zh': {
      'app_title': 'Listy',
      'settings_title': '应用设置',
      'language_label': '语言',
      'ai_config_title': 'AI配置',
      'ai_provider_label': 'AI提供商',
      'api_key_label': 'API密钥',
      'verify_connection': '验证连接',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'new_list': '新建列表',
      'rename_list': '重命名列表',
      'delete_list': '删除列表',
      'add_task_hint': '添加任务...',
      'add_item_hint': '添加物品...',
      'clear_list': '清空列表',
      'clear_completed': '删除已完成',
      'mode_todo': '待办模式',
      'mode_shopping': '购物模式',
      'urgent': '紧急',
      'medium': '中',
      'low': '低',
      'open': '待办',
      'cart': '购物车',
      'no_tasks': '无任务',
      'empty_cart': '清空购物车',
      'confirm_clear_list': '从该列表中删除所有项目？',
      'confirm_empty_cart': '从购物车中删除所有物品？',
      'confirm_clear_completed': '删除所有已完成的任务？',
      'camera_source_camera': '相机',
      'camera_source_gallery': '图库',
      'task_completed_msg': '任务已完成！',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']![key] ?? key;
  }
  
  static String getLabel(String code) {
    switch (code) {
      case 'de': return 'Deutsch';
      case 'en': return 'English';
      case 'ja': return '日本語';
      case 'zh': return '中文';
      default: return 'English';
    }
  }
}
